context("Filter functions")
test_that("test filter functions", {
  y1 <- make_seq(B2721, "all")
  y2 <- make_seq(B2721, c("ch1", "CHR4"))
  y3 <- make_seq(B2721, arg = y1$mrk.names[1:10])
  y4 <- make_seq(B2721, 1:10)
  expect_identical(y3,y4)
  plot(y4)
  y5 <- filter_redundant(y1)
  dat.filt1 <- filter_missing(B2721, inter = FALSE)
  dat.filt2 <- filter_missing(dat.filt1, inter = FALSE)
  expect_identical(dat.filt2, dat.filt1)
  dat.filt3 <- filter_missing(dat.filt1,
                              type = "individual", filter.thres = 0.04, inter = FALSE)
  i <- ceiling(seq(1, dat.filt3$n.mrk, length.out = 100))
  dat.sample <- subset_data(dat.filt3, select.mrk = dat.filt3$mrk.names[i])
  dat.filt <- filter_individuals(dat.sample, ind.to.remove = c("B2721.056", "B2721.065", "B2721.076"))
  sf1 <- filter_segregation(dat.filt, inter = FALSE)
  s2 <- make_seq(dat.filt, "Chr1")
  sf2 <- filter_segregation(input.obj = s2, inter = FALSE)
  expect_length(sf2, 3)
  expect_warning(mappoly2:::mappoly_chisq_test(dat.sample))
})
